### ISSUE TITLE
Possible issue with Logging trait

### ISSUE THREAD

**Issue by codingismy11to7** [lightbend-labs/scala-logging#16]
I apologize in advance if I'm off base here, I know very (VERY) little about scala macros, and not much more about java's invoking of virtual (?) / overridden methods.

I ran into issues where a parent class/trait extended the Logging trait and then the concrete class defined the logger method (manually or using slf4j LazyLogging or StrictLogging). Any usage of that logger in the parent class seems to be calling com.typesafe.scalalogging.Logger's methods - which are "???" and throw a NotImplementedError, instead of calling the overridden macro method from the slf4j Logger.

I simplified this issue and replicated in the REPL:

``` scala
scala> val logger = com.typesafe.scalalogging.slf4j.Logger(org.slf4j.LoggerFactory getLogger "test")
scala> (logger: com.typesafe.scalalogging.Logger) info "uheot"
scala.NotImplementedError: an implementation is missing
    at scala.Predef$.$qmark$qmark$qmark(Predef.scala:252)
    at com.typesafe.scalalogging.BaseLogger.info(Logger.scala:95)
```

**Comment by ibalashov** [comment]
> There's no more API, just an implementation for SLF4J.

`scala-logging-slf4j:2.1.2` still depends on troublesome `scala-logging-api_2.11`, which causes the following error:
```
java.lang.InstantiationError: com.typesafe.scalalogging.Logger
```

The workaround (for scala 2.11):
```
excludeDependencies ++= Seq(
  SbtExclusionRule("com.typesafe.scala-logging", "scala-logging-api_2.11")
)
```

Or should we not include `scala-logging-slf4j` altogether?
