### ISSUE TITLE
Scala 2.10 version of the scala-logging not in Maven Central?

### ISSUE THREAD

**Issue by rxin** [lightbend-labs/scala-logging#4]
I couldn't find the logging library from Maven Central or Sonatype using the dependency specified in the README:

```
"com.typesafe.scala-logging" %% "scala-logging-slf4j" % "2.0.1"
```

Searching Maven Central returns only the Scala 2.11-RC versions of scala-logging. Is there a different place to look?

http://search.maven.org/#search%7Cga%7C1%7Ccom.typesafe%20logging

There is a scalalogging-slf4j for Scala 2.10, but the version only goes up to 1.1.0, not the 2.x released. 

http://mvnrepository.com/artifact/com.typesafe/scalalogging-slf4j_2.10

Thanks.

**Comment by carlosmarin** [comment]
Since this came at the top of my google search, for others trying to do logging in Scala 2.x (< 2.11).

Use:

```
import com.typesafe.scalalogging.slf4j.Logger
import org.slf4j.LoggerFactory
val logger = Logger(LoggerFactory.getLogger("TheLoggerName"))
```

And @ build.sbt (libraryDependencies):
`"com.typesafe" %% "scalalogging-slf4j" % "1.1.0"`
