### ISSUE TITLE
New volunteer maintainer(s) needed

### ISSUE THREAD

**Issue by SethTisue** [lightbend-labs/scala-logging#407]
First, I want to thank @analytically for having done a great job with looking after this repo for a long time. 👏 🙏 

But we haven't heard from him in so long that I think the library is effectively unmaintained at this point and one or more new maintainers are needed. Anyone interested?

I don't use this library and I'm not interested in moving it forward myself, but I do have admin rights in lightbend-labs repos and can do administrative stuff. I've been merging e.g. clearly uncontroversial version bump PRs, but I'm not interested in taking on publishing duties.

Publishing is [sbt-ci-release](https://github.com/sbt/sbt-ci-release) based, so it's pretty easy; you basically just push a tag.

**Comment by jxnu-liguobin** [comment]
I hope I can

**Comment by SethTisue** [comment]
@analytically I see you commented on one of the other tickets. Are you open to having additional maintainers?

I can vouch for @jxnu-liguobin as having done a lot of helpful work in https://github.com/scala/scala .

I don't recall having run into you @mox692 , but offhand, your GitHub profile seems to show a good track record.

**Comment by analytically** [comment]
yeah sure that works for me, the more the merrier

**Comment by SethTisue** [comment]
@jxnu-liguobin @mox692 I've sent you both invites. thanks all!

**Comment by aparoha** [comment]
@SethTisue I would like to maintain. I have experience with Scala.

**Comment by SethTisue** [comment]
would the existing maintainers welcome having @aparoha join the team?
